const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

// ✅ Safe converter (VERY IMPORTANT)
function toArray(value) {
  if (!value) return [];
  if (Array.isArray(value)) return value;
  return [value];
}

function safeText(value) {
  return value ? String(value) : "N/A";
}

function generatePDF(reportPath, outputPath, confidenceScore) {
  const report = JSON.parse(fs.readFileSync(reportPath, "utf-8"));

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(fs.createWriteStream(outputPath));

  // 🎯 Title
  doc
    .fontSize(20)
    .fillColor("#22c55e")
    .text("Interview Report", { align: "center" });

  doc.moveDown();

  // 📊 Confidence Score
  doc
    .fontSize(14)
    .fillColor("black")
    .text(`Confidence Score: ${confidenceScore || 0}%`);

  doc.moveDown();

  // 🧠 Answers Section
  (report.answers || []).forEach((item, index) => {
    doc
      .fontSize(14)
      .fillColor("#000")
      .text(`Q${index + 1}: ${safeText(item.question)}`);

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("#333")
      .text(`Answer: ${safeText(item.answer)}`);

    doc.moveDown(0.5);

    if (item.feedback) {
      doc.text(`Score: ${item.feedback.score ?? "N/A"}`);
      doc.text(`Communication: ${safeText(item.feedback.communication)}`);
      doc.text(`Technical: ${safeText(item.feedback.technical)}`);

      // ✅ SAFE ARRAYS
      const strengths = toArray(item.feedback.strengths);
      const improvements = toArray(item.feedback.improvements);

      doc.text("Strengths:");
      strengths.forEach((s) => {
        doc.text(`• ${safeText(s)}`);
      });

      doc.text("Improvements:");
      improvements.forEach((i) => {
        doc.text(`• ${safeText(i)}`);
      });
    }

    doc.moveDown();
    doc.moveDown();
  });

  // 🏁 Footer
  doc
    .fontSize(10)
    .fillColor("gray")
    .text("Generated by Intervexa AI", { align: "center" });

  doc.end();
}

module.exports = generatePDF;
